# Generated by Django 5.0.2 on 2026-05-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0005_maestros_campus_maestros_sueldo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
